### ISSUE TITLE
楼主有没有相关博客笔记之类的？

### ISSUE THREAD

**Issue by Halfish** [lllcho/CAPTCHA-breaking#1]
感谢开源，代码很有参考价值，如果能加点解读和笔记之类的就更好了。比如预处理那块是怎么做的。

**Comment by lllcho** [comment]
以前简单的写过思路，忘了贴过来，谢谢提醒。[戳这里](http://bbs.pkbigdata.com/topic/e0286749ba3245bc96444122cc9877db.html)

**Comment by Halfish** [comment]
嗯，看懂了。原来（字数分类＋等距切分）看似简单的思路，却可以做到很高的准确率，思路开拓了不少。谢谢！
